//note: remember the '#' symbol
export const grey = '#262626';
export const blue = '#66b3ff';
export const palerBlue = '#99ccff';
export const paleGreyBlue = '#ecf2ff';
export const mediumGreyBlue = '#80a8ff';
export const panelDarkGrey = '#333';
export const panelMediumGrey = '#999';
export const panelLightGrey = '#ddd';